
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/softwarebb/spring-cloud
          force-pull: true
      label: main
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zoneUrl: http://localhost:8761/eureka/