
spring:
  application:
    name: config-client
  cloud:
    config:
      label: main
      profile: dev
server:
  port: 8881
eureka:
  client:
    service-url:
      default-zoneUrl: http://localhost:8761/eureka/